# Treinando numpy - vetor, matriz e funções 

In [76]:
import numpy as np

In [77]:
my_list = [1,2,3]

In [78]:
my_list

[1, 2, 3]

Criando array numpy com a lista acima

In [79]:
np.array(my_list)

array([1, 2, 3])

In [80]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

Criando matriz

In [81]:
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Criando array com elementos de 0 a 9 com arange

In [82]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Criando array com elementos de 0 a 9, somando de 3 em 3

In [83]:
np.arange(0,10,3)

array([0, 3, 6, 9])

Criando array com zeros

In [84]:
np.zeros(3)

array([0., 0., 0.])

In [85]:
arr = np.zeros(5)

In [86]:
arr

array([0., 0., 0., 0., 0.])

In [87]:
arr = np.zeros((5,5))

In [88]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Criando arrays de 1

In [89]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [90]:
np.ones(3)

array([1., 1., 1.])

Criando matriz identidade

In [91]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Linspace

np.linspace(inicio, fim, quantos números igualmente espaçados)

In [92]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

Criando array com números aleatórios

In [93]:
np.random.rand(5)

array([0.24854008, 0.59269783, 0.0532714 , 0.31323346, 0.38449422])

In [94]:
np.random.rand(5) * 100 # multiplicando array por 100

array([54.90442478, 97.0885961 , 33.23422012, 59.15030532, 77.97911285])

Criando matriz de números aleatórios

In [95]:
np.random.rand(5,4) 

array([[0.21849762, 0.23705192, 0.86542416, 0.30833395],
       [0.70377888, 0.34373971, 0.48462088, 0.2471347 ],
       [0.08110642, 0.6660173 , 0.6987416 , 0.0248943 ],
       [0.27150096, 0.93389747, 0.05941935, 0.34841061],
       [0.64237211, 0.74415034, 0.16415507, 0.79902175]])

Criando matriz com profundidade

In [96]:
np.random.rand(5,4,4) 

array([[[0.10691956, 0.57078976, 0.84690053, 0.6505129 ],
        [0.16563112, 0.31316971, 0.02883023, 0.84895046],
        [0.63326795, 0.68216894, 0.03581919, 0.91851307],
        [0.46239005, 0.26597796, 0.32569883, 0.4976712 ]],

       [[0.84795662, 0.34709605, 0.3490303 , 0.03713486],
        [0.4728711 , 0.30336896, 0.81140969, 0.36462876],
        [0.04399343, 0.77296133, 0.95472925, 0.55102194],
        [0.22423958, 0.4682253 , 0.92922787, 0.83860037]],

       [[0.35711671, 0.48225945, 0.6813416 , 0.77652767],
        [0.41298867, 0.61176314, 0.6162126 , 0.58469165],
        [0.73435096, 0.90172886, 0.26636897, 0.01313216],
        [0.75449437, 0.6927493 , 0.17844577, 0.41548568]],

       [[0.0880036 , 0.68388606, 0.90077257, 0.70149834],
        [0.4054828 , 0.43430875, 0.97596649, 0.96777904],
        [0.04999636, 0.76854412, 0.36481491, 0.1027428 ],
        [0.60988507, 0.72899331, 0.09981679, 0.1444609 ]],

       [[0.56016387, 0.47001023, 0.20756507, 0.91097739],
      

Criando matriz com numeros inteiros aleatórios de 0 a 100

In [97]:
np.random.randint(0,100, 10)

array([55, 97, 61, 30, 77, 11, 17, 59, 34, 28])

Criando array com round(conjunto de números, número de casas decimais)

In [98]:
np.round(np.random.rand(4) * 100, 0) 

array([100.,  24.,  66.,  52.])

In [99]:
arr = np.random.rand(25)

In [100]:
arr

array([0.70868771, 0.1699262 , 0.20687425, 0.08268902, 0.42401561,
       0.12582637, 0.13717627, 0.7305847 , 0.74623927, 0.85704944,
       0.27691631, 0.53178319, 0.86696107, 0.91005477, 0.34151522,
       0.24732791, 0.56849784, 0.72357922, 0.06844621, 0.59855361,
       0.14391865, 0.58009138, 0.4305943 , 0.18836453, 0.24237022])

Transformando vetor em matriz por meio do reshape

In [101]:
arr = arr.reshape((5,5))

In [102]:
arr

array([[0.70868771, 0.1699262 , 0.20687425, 0.08268902, 0.42401561],
       [0.12582637, 0.13717627, 0.7305847 , 0.74623927, 0.85704944],
       [0.27691631, 0.53178319, 0.86696107, 0.91005477, 0.34151522],
       [0.24732791, 0.56849784, 0.72357922, 0.06844621, 0.59855361],
       [0.14391865, 0.58009138, 0.4305943 , 0.18836453, 0.24237022]])

In [103]:
arr.shape

(5, 5)

Procurando maior elemento do array

In [104]:
arr.max() 

0.910054771589712

Procurando menor elemento do array

In [105]:
arr.min() 

0.06844621074109947

Mostrando posição do maior elemento

In [106]:
arr.argmax()

13

Mostrando posição do menor elemento

In [107]:
arr.argmin()

18