# Numpy - selecionando elementos do array

In [2]:
import numpy as np

Criando array

In [3]:
arr = np.arange(0,30,3)

In [4]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [5]:
arr[2]

6

In [6]:
arr[2:8]

array([ 6,  9, 12, 15, 18, 21])

In [7]:
arr[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [8]:
arr[:5]

array([ 0,  3,  6,  9, 12])

Modificando elementos

In [9]:
arr[2:] = 100

In [10]:
arr

array([  0,   3, 100, 100, 100, 100, 100, 100, 100, 100])

### Selecionando elementos de matrizes

Transformando array em Matriz

In [11]:
arr = np.arange(50).reshape((5,10)) #Bidimensionalizando

In [12]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [13]:
arr.shape

(5, 10)

In [14]:
arr[2][0]

20

In [15]:
arr[:3][:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [16]:
arr2 = arr[:2]

In [17]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [18]:
 arr2[:] = 100 #Python entende que esse arr2 é uma referencia a fatia correspondente ao array

In [20]:
arr # Matriz arr fica alterada

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]])

In [24]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

Como corrigir ? metodo .copy()

In [26]:
arr2 = arr[:2].copy() # Assim, o arr2 será uma cópia e não uma referência

In [27]:
arr2

array([[100, 100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100, 100]])

Slices de linhas e colunas

In [30]:
arr[0:3,:5] # Slice com 3 linhas e

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [ 20,  21,  22,  23,  24]])

Quais elementos são maiores que 50?

In [31]:
arr>50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [21]:
bol = arr >50 # variável recebe somente os elementos de arr maiores que 50

In [22]:
arr[bol] # printando elementos maiores que 50

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

### Utilizando o linspace 

In [23]:
arrr = np.linspace(0,100,30)

In [24]:
arrr

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [25]:
arrr.shape

(30,)

In [26]:
arrr = arrr.reshape(3,10) # os dois parametros multiplicados tem que dar o tamanho do array

In [27]:
arrr

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [28]:
arrr[0:2,2:3]

array([[ 6.89655172],
       [41.37931034]])

In [29]:
arrr[0:2,2]

array([ 6.89655172, 41.37931034])